/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.DBConnection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author John
 */
public class SaleReview extends javax.swing.JFrame {

    /**
     * Creates new form SaleReview
     */
    DefaultTableModel model;
    private void TableShow()
    {
        Models.ReviewModel.listReview.clear();
        DBConnection connect=new DBConnection();
        connect.select("SellReview","");
        String [] column={"OPeration_ID","Parcode","Med_Nam","price","Retail","Quantity","Emp_ID","Sell_Date","Sell_Time","ID_Med"};
        model=new DefaultTableModel();
       model.addColumn(column[0]);
       model.addColumn(column[1]);
       model.addColumn(column[2]);
       model.addColumn(column[3]);
       model.addColumn(column[4]);
       model.addColumn(column[5]);
       model.addColumn(column[6]);
       model.addColumn(column[7]);
       model.addColumn(column[8]);
       model.addColumn(column[9]);
       String []row=new String[10];
       //"OPeration_ID","Parcode","Med_Nam","price","Retail",
       //"Quantity","Emp_ID","Sell_Date","Sell_Time","ID_Med"};
       
        for (int i = 0; i < Models.ReviewModel.listReview.size(); i++) {
            row[0]=Models.ReviewModel.listReview.get(i).getOP_ID()+"";
            row[1]=Models.ReviewModel.listReview.get(i).getParcode()+"";
            row[2]=Models.ReviewModel.listReview.get(i).getMed_Name();
            row[3]=Models.ReviewModel.listReview.get(i).getPrice()+"";
            row[4]=Models.ReviewModel.listReview.get(i).getRetail()+"";
            row[5]=Models.ReviewModel.listReview.get(i).getQuantity_M()+"";
            row[6]=Models.ReviewModel.listReview.get(i).getEmp_ID()+"";
            row[7]=Models.ReviewModel.listReview.get(i).getSell_Date()+"";
            row[8]=Models.ReviewModel.listReview.get(i).getSell_Time();
            row[9]=Models.ReviewModel.listReview.get(i).getID_Med()+"";
            model.addRow(row);
        }
 
        
        
       tab.setModel(model);
        
    }
    
    private void calculatePrice()
    {
        double price=0.0;
        for (int i = 0; i < tab.getRowCount(); i++) {
            price=price+Double.parseDouble(tab.getValueAt(i, 3).toString());    
        }
        lblprice.setText(price+"");
    }
    
    private void calculateRetail()
    {
        double price=0.0;
        for (int i = 0; i < tab.getRowCount(); i++) {
            price=price+Double.parseDouble(tab.getValueAt(i, 4).toString());    
        }
        
        lblRetail.setText((Double.parseDouble(lblprice.getText())-price)+"");
    }
    
    private void search(int column)
    {
        for (int i = tab.getRowCount()-1; i >=0; i--) {
                if(!tab.getValueAt(i, column).toString().equals(search.getText()))
                {
                   model.removeRow(i);
                }
            }
    }
    
    public SaleReview() {
        initComponents();
        this.setSize(1200, 700);
        this.setLocationRelativeTo(null);
        TableShow();
        calculatePrice();
        calculateRetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox();
        search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        lblRetail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 700));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Search:");

        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Operation_ID", "Parcode", "Med_Name", "Price", "Retail", "Quantity", "Emp_ID", "Sell_Date", "Sell_Time", "ID_Med" }));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tab.setBorder(new javax.swing.border.MatteBorder(null));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tab);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Total Sales:");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setText("Total Earn:");

        lblprice.setText("0");

        lblRetail.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(lblprice, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(lblRetail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblprice))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblRetail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton3))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HomePage p=new HomePage();
            p.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TableShow();
        search.setText("");
        calculatePrice();
        calculateRetail(); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TableShow();
//Operation_ID, Parcode, Med_Name, Price, Retail, Quantity, Emp_ID, Sell_Date, Sell_Time, ID_Med
        if(cb.getSelectedItem().equals("Operation_ID"))
        {
            search(0);
        }else if(cb.getSelectedItem().equals("Parcode"))
        {
            search(1);
        }else if(cb.getSelectedItem().equals("Med_Name"))
        {
            search(2);
        }else if(cb.getSelectedItem().equals("Price"))
        {
            search(3);
        }else if(cb.getSelectedItem().equals("Retail"))
        {
            search(4);
        }else if(cb.getSelectedItem().equals("Quantity"))
        {
           search(5);
        }else if(cb.getSelectedItem().equals("Emp_ID"))
        {
            search(6);
        }else if(cb.getSelectedItem().equals("Sell_Date"))
        {
            search(7);
        }else if(cb.getSelectedItem().equals("Sell_Time"))
        {
            search(8);
        }else if(cb.getSelectedItem().equals("ID_Med"))
        {
            search(9);
        }
       calculatePrice();
        calculateRetail(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleReview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRetail;
    private javax.swing.JLabel lblprice;
    private javax.swing.JTextField search;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
